# Generated by Django 4.2.7 on 2023-11-21 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 21, 8, 57, 54, 829720, tzinfo=datetime.timezone.utc)),
        ),
    ]
