# Generated by Django 4.2.7 on 2023-11-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_user_product_normalized_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='normalized_name',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
