# Generated by Django 4.2.7 on 2023-11-22 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 22, 8, 39, 35, 799828, tzinfo=datetime.timezone.utc)),
        ),
    ]
